# Workflow derived from https://github.com/rstudio/shiny-workflows
#
# NOTE: This Shiny team GHA workflow is overkill for most R packages.
# For most R packages it is better to use https://github.com/r-lib/actions
on:
  push:
    branches: [main, rc-**]
  pull_request:
  schedule:
    - cron: "0 8 * * 1" # every monday
  workflow_dispatch:

name: Package checks

jobs:
  website:
    uses: rstudio/shiny-workflows/.github/workflows/website.yaml@v1
    with:
      check-title: false
  routine:
    uses: rstudio/shiny-workflows/.github/workflows/routine.yaml@v1
    with:
      format-r-code: true
  R-CMD-check:
    uses: rstudio/shiny-workflows/.github/workflows/R-CMD-check.yaml@v1
    with:
      cache-version: "regular-1"

  R-CMD-check-with-dont-test:
    uses: rstudio/shiny-workflows/.github/workflows/R-CMD-check.yaml@v1
    with:
      extra-check-args: '"--run-donttest"'
      cache-version: "donttest-1"

  cpp-extra-test:
    name: cpp-extra-test
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout GitHub repo
        uses: rstudio/shiny-workflows/.github/internal/checkout@v1

      - name: Install R, system dependencies, and package dependencies
        uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          needs: check
          extra-packages: any::pkgload
      - name: Run testthat on test-cpp.R
        run: |
          pkgload::load_all()
          testthat::test_file(file.path("tests", "testthat", "test-cpp.R"))
        shell: Rscript {0}
